# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
FROM node:18

#=== Devcontainer ONLY code ====

# Switch to 'devContainer' user
USER node
