on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.getbody.outputs.message }}
    steps:
      - uses: actions/checkout@v2
      - id: getbody
        uses: craigloewen-msft/GitGudSimilarIssues@main
        with:
          issuetitle: ${{ github.event.issue.title }}
          repo: ${{ github.repository }}
          eucldistancetolerance: "1.5"
  add-comment:
    needs: greet
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: ${{ needs.greet.outputs.message }}